#!/usr/bin/env python3
"""Rebuild the GPC category-scope table in cloudflare/feedspark-deck/src/labelguard.js.

Google's product data spec ties four attributes to a CATEGORY: colour, gender and age_group
are required for Clothing & Accessories (ID 166, gender/age_group minus a short list of
exempt sub-categories), size for Clothing (1604) and Shoes (187). Google's clothing best
practice page (answer 7348545) adds material and pattern for the same 166 tree. The Golden
Record scores those attributes only over the products in those categories, so it has to
recognise a product's category in whatever language the feed carries it (the estate ships
en-GB, en-US, de-DE, fr-FR, nl-NL, da-DK and es-ES today) or as a numeric ID.

This script fetches Google's own taxonomy-with-ids files for every locale Google publishes,
and writes, between the GPC-SCOPE:DATA markers:
  GPC_ROOT   — every locale's name for Clothing & Accessories (ID 166)
  GPC_TAILS  — every locale's path BELOW that root for each other ID the rules name (every
               one of them sits under 166, so a tail is matched after a 166 root)
  GPC_IDS    — the numeric IDs inside each of those IDs' subtrees
  GPC_ROOTS  — every locale's top-level category names (so a value can be told apart from
               a value the scope cannot read at all)

Run:  python3 tools/build_gpc_scope.py            (cache in /tmp/gpcloc)
Then: cp cloudflare/feedspark-deck/src/labelguard.js docs/labelguard_engine.js
"""
import os
import re
import sys
import unicodedata
import urllib.request

LOCALES = ['en-US', 'en-GB', 'en-AU', 'de-DE', 'de-CH', 'fr-FR', 'fr-CH', 'nl-NL', 'da-DK', 'es-ES',
           'it-IT', 'sv-SE', 'no-NO', 'pl-PL', 'pt-BR', 'cs-CZ', 'ja-JP', 'tr-TR', 'ru-RU', 'fi-FI',
           'sk-SK', 'ro-RO', 'el-GR', 'hu-HU', 'ar-SA', 'zh-CN']
# the IDs the scope rules in labelguard.js name — keep in step with GPC_SCOPE there
KEY_IDS = ['166', '1604', '187', '193', '4179', '180', '1893', '5385', '1856', '2427', '5123',
           '175', '5841', '6277', '6460', '6170', '6870', '7471', '5207', '5114']
CACHE = '/tmp/gpcloc'
TARGET = os.path.join(os.path.dirname(__file__), '..', 'cloudflare', 'feedspark-deck', 'src', 'labelguard.js')
START, END = '// GPC-SCOPE:DATA-START', '// GPC-SCOPE:DATA-END'


def norm(s):
    # mirrors gpcNorm() in labelguard.js: NFC, lower-case, stray leading punctuation off,
    # every segment trimmed and re-joined on ' > '
    s = unicodedata.normalize('NFC', s).lower()
    s = re.sub(r'^[^\w]+', '', s)
    return ' > '.join(p.strip() for p in s.split('>') if p.strip())


def load(loc):
    os.makedirs(CACHE, exist_ok=True)
    f = os.path.join(CACHE, loc + '.txt')
    if not os.path.exists(f) or os.path.getsize(f) < 1000:
        url = 'https://www.google.com/basepages/producttype/taxonomy-with-ids.%s.txt' % loc
        with urllib.request.urlopen(url, timeout=30) as r:
            open(f, 'wb').write(r.read())
    out = {}
    for line in open(f, encoding='utf-8'):
        m = re.match(r'^(\d+) - (.+)$', line.strip())
        if m:
            out[m.group(1)] = m.group(2)
    if len(out) < 5000:
        raise SystemExit('%s: only %d categories — not a taxonomy file' % (loc, len(out)))
    return out


def main():
    paths = {k: [] for k in KEY_IDS}
    root166 = []
    roots = []
    us = None
    for loc in LOCALES:
        t = load(loc)
        if loc == 'en-US':
            us = t
        r166 = norm(t['166'])
        if r166 not in root166:
            root166.append(r166)
        for k in KEY_IDS:
            if k not in t:
                raise SystemExit('%s: ID %s missing' % (loc, k))
            if k == '166':
                continue
            p = norm(t[k])
            if not p.startswith(r166 + ' > '):
                raise SystemExit('%s: ID %s is not under 166' % (loc, k))
            tail = p[len(r166) + 3:]
            if tail not in paths[k]:
                paths[k].append(tail)
        for v in t.values():
            r = norm(v.split('>')[0])
            if r and r not in roots:
                roots.append(r)
    ids = {}
    for k in KEY_IDS:
        base = us[k]
        ids[k] = sorted((i for i, v in us.items() if v == base or v.startswith(base + ' > ')), key=int)
    js = lambda s: "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"
    lines = [START,
             '// generated by tools/build_gpc_scope.py from Google\'s taxonomy-with-ids files (%d locales,' % len(LOCALES),
             '// version 2021-09-21 — Google\'s current taxonomy); do not edit by hand',
             'const GPC_ROOT = [%s];' % ', '.join(js(r) for r in root166),
             'const GPC_TAILS = {']
    for k in KEY_IDS:
        if k != '166':
            lines.append('  %s: [%s],' % (js(k), ', '.join(js(p) for p in paths[k])))
    lines.append('};')
    lines.append('const GPC_IDS = {')
    for k in KEY_IDS:
        lines.append("  %s: '%s'," % (js(k), ','.join(ids[k])))
    lines.append('};')
    lines.append('const GPC_ROOTS = [%s];' % ', '.join(js(r) for r in roots))
    lines.append(END)
    block = '\n'.join(lines)
    src = open(TARGET, encoding='utf-8').read()
    a, b = src.find(START), src.find(END)
    if a < 0 or b < 0:
        raise SystemExit('markers not found in ' + TARGET)
    src = src[:a] + block + src[b + len(END):]
    open(TARGET, 'w', encoding='utf-8').write(src)
    print('GPC scope table: %d locales, %d paths, %d roots, %d bytes' % (
        len(LOCALES), len(root166) + sum(len(v) for v in paths.values()), len(roots), len(block.encode('utf-8'))))


if __name__ == '__main__':
    main()
