// Phone layer harness (pure node, CI-safe — the Playwright render check is tools/check_mobile.js in presync).
// Pins what makes the phone view MIRROR the desktop (Ray, 15 Sep 2026): the layer is injected on every
// app page for every signin, the module nav node becomes the bottom bar (same anchors), nothing a page
// used to hide under a max-width rule stays hidden, and the two render tripwires carry the widget.
import fs from 'node:fs';
const read = (p) => fs.readFileSync(new URL('../' + p, import.meta.url), 'utf8');
const W = read('docs/mobile_widget.html'), WK = read('cloudflare/feedspark-deck/src/worker.js');
const DARK = read('tools/check_darkmode.js'), MOB = read('tools/check_mobile.js'), PRE = read('tools/presync.sh');
const DG = read('docs/digest_widget.html');
let pass = 0, fail = 0;
const t = (name, ok, why) => { if (ok) { pass++; console.log('  ✓ ' + name); } else { fail++; console.log('  ✗ ' + name + (why ? ' — ' + why : '')); } };
const media = W.match(/@media \(max-width:760px\)\{([\s\S]*)\n\}\n<\/style>/);
t('the layer is a single ≤760px media block', !!media);
const css = media ? media[1] : '';
console.log('· chrome');
t('the module nav node itself becomes the fixed bottom bar (same anchors, same order, same ▦ bundling)', /#tb-modules\{display:flex!important;position:fixed;left:0;right:0;bottom:0/.test(css));
t('every bar item shows its label (the desktop tooltip text) under the icon', /#tb-modules a\.tbm::after\{content:attr\(data-lbl\)/.test(css));
t('the desktop collapse toggle collapses the bar too (mirror), the ▦ sheet still lists every module', /:root\.nav-collapsed #tb-modules\{display:none!important\}/.test(css) && /All modules/.test(W));
t('the topbar drops its backdrop blur on phones (it would become the containing block of the fixed bar + sheets)', /\.topbar\{backdrop-filter:none!important/.test(css));
t('the ▦ menu, presence popover, view-as pill and customizer become bottom sheets above the bar', /#fcc-apps-menu\{position:fixed!important/.test(css) && /\.pz-pop\{left:8px!important/.test(css) && /#fcc-viewas\{top:auto!important/.test(css) && /#fcc-navcz\{width:100%!important/.test(css));
t('the Feed Chat bubble rides above the bar', /#fcc-fcb\{bottom:calc\(var\(--fcc-bar\)/.test(css));
t('body reserves the bar height (safe-area aware)', /body\{padding-bottom:calc\(var\(--fcc-bar\) \+ env\(safe-area-inset-bottom/.test(css));
console.log('· mirror — nothing a page hid under a max-width rule stays hidden');
t('Golden Record per-attribute actions + notes are shown', /\.at-act\{display:flex!important/.test(css) && /\.at-note\{display:block!important/.test(css));
t("the brief composer's context rail is shown", /\.bs-ctx\{display:block!important/.test(css));
t('the home CTA link is shown', /\.wf-cta \.wf-go\{display:inline-flex!important/.test(css));
t('the AI Quote rate / line columns are shown and the grid pans', /\.qrow \.col-rate,\.qrow \.col-line[^{]*\{display:block!important/.test(css) && /\.qrows\{display:block;overflow-x:auto/.test(css));
t('the court sub-labels are shown', /\.court \.ct-s\{display:block!important/.test(css));
console.log('· pan, don\'t crush');
t('wide tables and min-width workbenches get a scrolling frame from the sweep', /function pan\(el\)/.test(W) && /querySelectorAll\('table'\)/.test(W) && /parseFloat\(cs\.minWidth\)/.test(W));
t('the sweep re-runs on DOM mutations and on resize, never inside the bar / sheets', /MutationObserver/.test(W) && /closest\('#tb-modules,#fcc-apps-menu,\.pz-pop'\)/.test(W));
t('inputs render at 16px (no iOS zoom on focus) and buttons get a thumb-sized target', /select,textarea\{font-size:16px!important\}/.test(css) && /a\.btn\{min-height:36px\}/.test(css));
console.log('· wiring');
t('the worker injects the layer on app pages for EVERY signin (not owner-gated)',
  /^\s*html = inject\(html, MOBILEW\);$/m.test(WK) && !/realOwner\([^)]*\)\)[^\n]*MOBILEW/.test(WK));
t('the worker imports the widget as a Text module', /import MOBILEW from "\.\.\/\.\.\/\.\.\/docs\/mobile_widget\.html";/.test(WK));
t('the dark tripwire renders pages WITH the phone layer', /'apps_widget\.html', 'mobile_widget\.html'/.test(DARK));
t('the phone tripwire renders every app page at 390px and fails on overflow / tall header / lost bar / hidden desktop controls', /devices\['iPhone 13'\]/.test(MOB) && /horizontal overflow/.test(MOB) && /topbar ' \+ m\.tbH \+ 'px tall/.test(MOB) && /hidden on the phone but visible on desktop/.test(MOB));
t('presync runs the phone tripwire after the dark one', /check_darkmode\.js[\s\S]*check_mobile\.js/.test(PRE));
console.log('· skim view — every section one tap row, folded by default (Ray, 18 Sep 2026, the Meta Ads Manager example)');
const dgMedia = DG.match(/@media \(max-width:760px\)\{([\s\S]*)\n\}\n<\/style>/);
t('the skim layer is its own injected widget, phone-only CSS + a FCC-DIGEST script', /FCC-DIGEST/.test(DG) && !!dgMedia && /window\.FCCDigest = \{ state: state, expandAll: expandAll, collapseAll: collapseAll/.test(DG));
t('the worker injects it after the phone layer for every signin', /^\s*html = inject\(html, DIGESTW\);$/m.test(WK) && WK.indexOf('inject(html, MOBILEW)') < WK.indexOf('inject(html, DIGESTW)') && /import DIGESTW from "\.\.\/\.\.\/\.\.\/docs\/digest_widget\.html";/.test(WK));
t('two shapes, one mechanism: a block that contains its heading (A) and a heading above its siblings (B)', /function partsA\(d\)/.test(DG) && /function partsB\(d\)/.test(DG) && /function ownHeads\(b\)/.test(DG));
t('the fold hides by class and the desktop media query never applies it (nothing removed, no node moved)', /\.fcc-dg-x,\.fcc-dg-r\{display:none!important\}/.test(dgMedia ? dgMedia[1] : '') && !/\.removeChild\(d\.heading|\.remove\(\);\s*\/\/ heading/.test(DG));
t("the widget's own nodes are invisible outside the phone width (a resize to desktop leaves no chevron text)", /^\.fcc-dg-ch,\.fcc-dg-dg,\.fcc-dg-bar,\.fcc-dg-more\{display:none\}$/m.test(DG));
t('default = closed when the page has two or more sections; a lone section is nothing to skim among', /var want = g\.late \? true : n < 2;/.test(DG));
t('a section that appears AFTER boot opens — it arrived because the reader did something', /var late = Date\.now\(\) - bootAt > BOOT_MS/.test(DG) && /BOOT_MS = 3000/.test(DG));
t('what a device opened is remembered per device (localStorage fcc-m-open), never shared state', /KEY = 'fcc-m-open'/.test(DG) && !/\/api\/state/.test(DG));
t('an expand or collapse made this visit holds through the boot window (the tripwire\'s silent expand included)', /if \(g\.pinned\) \{ g\.decided = true; continue; \}/.test(DG) && /digests\[i\]\.pinned = true; if \(!\(opts && opts\.silent\)\)/.test(DG));
t('the heading keeps its own buttons: a tap on one never toggles the fold', /closest\('button,a,input,select,label,textarea,\.info-pop'\)\) return;/.test(DG));
t('a heading that already carries the page\'s own toggle is left to the page (styled into the row rhythm, tap forwards)', /function ownToggle\(h\)/.test(DG) && /function decorateOwn\(h\)/.test(DG) && /if \(ownToggle\(h\)\) \{ decorateOwn\(h\); continue; \}/.test(DG));
t('rows are ordered by DOCUMENT position whichever pass found them, so the bar sits above the first', /compareDocumentPosition\(y\) & 4/.test(DG));
t('the row digest reads the section: the page\'s own word, KPI headlines, alert counts, rows, items', /data-m-digest/.test(DG) && /collect\(list, '\.kpi', 12\)/.test(DG) && /collect\(list, '\.al-row', 400\)/.test(DG) && /function repeated\(list\)/.test(DG));
t('a long table shows 8 rows behind "Show all N rows" (cap at 10) — lifted for good once tapped', /ROWS_SHOW = 8, ROWS_CAP = 10/.test(DG) && /'Show all ' \+ rows\.length \+ ' rows'/.test(DG));
t('a #hash into a folded section opens it and scrolls there', /function hashOpen\(\)/.test(DG) && /addEventListener\('hashchange', hashOpen\)/.test(DG));
t('never inside chrome, a dialog, a rail, a print sheet, the chat or the hero', /\.modal,\[role=dialog\],\.drawer,\.ck-rail/.test(DG) && /\.chat-card,\[data-embed\]/.test(DG) && /\.hero,\.footmark/.test(DG));
t('Expand all / Collapse all sit above the first row (only when there is something to skim)', /if \(n < 2 \|\| !first\) \{ if \(bar\.parentNode\) bar\.parentNode\.removeChild\(bar\); return; \}/.test(DG));
t('the KPI strip reads as a 3-up summary band (kpis + the home stat strip); Leadership\'s hub is one row of tiles', /\.kpis,\.statstrip\{display:grid!important;grid-template-columns:repeat\(3,minmax\(0,1fr\)\)!important/.test(DG) && /\.hub\{grid-template-columns:repeat\(3,minmax\(0,1fr\)\)!important/.test(DG));
t('the phone tripwire asserts the fold at first paint on a fresh device, then expands everything before the parity count', /FCCDigest\.state\(\)/.test(MOB) && /FCCDigest\.expandAll\(\{ silent: true, caps: true \}\)/.test(MOB) && /skim view: ' \+ \(sk\.n - sk\.closed\) \+ ' of ' \+ sk\.n \+ ' sections open at first paint/.test(MOB) && MOB.indexOf("FCCDigest.expandAll") < MOB.indexOf("res[mode] = await p.evaluate(COLLECT)"));
t('both browser tripwires render pages WITH the skim layer', /'mobile_widget\.html', 'digest_widget\.html'/.test(MOB) && /'mobile_widget\.html', 'digest_widget\.html'/.test(DARK));
console.log('\n' + pass + ' passed, ' + fail + ' failed');
process.exit(fail ? 1 : 0);
